### ISSUE TITLE
qb-shops:247clerk

### ISSUE THREAD

**Issue by Andyauk** [Github-Samuel/qb-target#1]
qb-shops:247clerk don't seem to be working for me, i added all the info you added.

**Comment by Github-Samuel** [comment]
You need to put this at the end of your qb-shops, main.lua
Then clear cache and restart the server fully!


AddEventHandler('qb-shops:247clerk', function(shop, itemData, amount)
        local InRange = false
        local PlayerPed = PlayerPedId()
        local PlayerPos = GetEntityCoords(PlayerPed)

        for shop, _ in pairs(Config.Locations) do
            local position = Config.Locations[shop]["coords"]
            for _, loc in pairs(position) do
                local dist = #(PlayerPos - vector3(loc["x"], loc["y"], loc["z"]))
                if dist < 10 then

                        local ShopItems = {}
                        ShopItems.items = {}
                        QBCore.Functions.TriggerCallback('qb-shops:server:getLicenseStatus', function(result)
                            ShopItems.label = Config.Locations[shop]["label"]
                            if Config.Locations[shop].type == "weapon" then
                                if result then
                                    ShopItems.items = Config.Locations[shop]["products"]
                                else
                                    for i = 1, #Config.Locations[shop]["products"] do
                                        if not Config.Locations[shop]["products"][i].requiresLicense then
                                            table.insert(ShopItems.items, Config.Locations[shop]["products"][i])
                                        end
                                    end
                                end
                            else
                                ShopItems.items = Config.Locations[shop]["products"]
                            end
                            ShopItems.slots = 30
                            TriggerServerEvent("inventory:server:OpenInventory", "shop", "Itemshop_"..shop, ShopItems)
                        end)
                    end
                end
            end

        if not InRange then
            Citizen.Wait(5000)
        end
        Citizen.Wait(5)
end)

**Comment by Andyauk** [comment]
i found what it was, you added the target stuff in Config.TargetBones = { when  it should be in Config.TargetModels = {

**Comment by Github-Samuel** [comment]
Thanks for informing me, sorted it out now!

**Comment by Andyauk** [comment]
> Thanks for informing me, sorted it out now!

here to help, will you be adding the Clothing and Barber tattoo. 

i also noticed that it doesn't check if you have a weapon licensee -+

**Comment by Github-Samuel** [comment]
Hello! Thanks for reporting that issue, I've updated the repo and it should now check for licenses

Check the bottom of the repo to know what to replace :)
